/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:07 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol CommerceRemoteUIDelegateDelegate <NSObject>
@required
-(void)commerceDelegate:(id)arg1 willPresentObjectModel:(id)arg2 page:(id)arg3;
-(void)commerceDelegate:(id)arg1 loadDidFailWithError:(id)arg2;
-(void)commerceDelegateDidCancel:(id)arg1;

@end

