/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:08 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@interface PSAboutTextSheetViewController : UIViewController
+(void)presentAboutSheetTitled:(id)arg1 attributedText:(id)arg2 fromViewController:(id)arg3 ;
-(void)setAttributedText:(id)arg1 ;
-(void)loadView;
-(void)donePressed;
@end

