/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:07 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

//#import <Preferences/Preferences-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITextInput.h>

@protocol PSPasscodeFieldDelegate;
@class NSMutableArray, NSMutableString, UIColor, NSArray, NSString;

@interface PSPasscodeField : UIView <UIKeyInput> {

	NSMutableArray* _dashViews;
	NSMutableArray* _dotViews;
	NSMutableArray* _digitViews;
	NSMutableString* _stringValue;
	BOOL _securePasscodeEntry;
	id<PSPasscodeFieldDelegate> _delegate;
	unsigned long long _numberOfEntryFields;
	UIColor* _foregroundColor;
	long long _keyboardAppearance;
	NSArray* _fieldSpacing;

}

@property (assign,nonatomic) id<PSPasscodeFieldDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfEntryFields;                     //@synthesize numberOfEntryFields=_numberOfEntryFields - In the implementation block
@property (assign,nonatomic) BOOL securePasscodeEntry;                                   //@synthesize securePasscodeEntry=_securePasscodeEntry - In the implementation block
@property (nonatomic,retain) UIColor * foregroundColor;                                  //@synthesize foregroundColor=_foregroundColor - In the implementation block
//@property (assign,nonatomic) long long keyboardAppearance;                               //@synthesize keyboardAppearance=_keyboardAppearance - In the implementation block
@property (nonatomic,retain) NSArray * fieldSpacing;                                     //@synthesize fieldSpacing=_fieldSpacing - In the implementation block
@property (readonly) unsigned long hash;
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) long autocapitalizationType;
@property (assign,nonatomic) long autocorrectionType;
@property (assign,nonatomic) long spellCheckingType;
@property (assign,nonatomic) long keyboardType;
@property (assign,nonatomic) long returnKeyType;
@property (assign,nonatomic) BOOL enablesReturnKeyAutomatically; 
@property (assign,getter=isSecureTextEntry,nonatomic) BOOL secureTextEntry; 
-(void)setDelegate:(id<PSPasscodeFieldDelegate>)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<PSPasscodeFieldDelegate>)delegate;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(long)keyboardAppearance;
-(BOOL)hasText;
-(void)insertText:(id)arg1 ;
-(void)deleteBackward;
-(void)setSecureTextEntry:(BOOL)arg1 ;
-(BOOL)isSecureTextEntry;
-(long)keyboardType;
-(void)setKeyboardAppearance:(long long)arg1 ;
-(id)stringValue;
-(void)setStringValue:(id)arg1 ;
-(unsigned long long)numberOfEntryFields;
-(void)setNumberOfEntryFields:(unsigned long long)arg1 ;
-(UIColor *)foregroundColor;
-(void)setForegroundColor:(UIColor *)arg1 ;
-(void)passcodeFieldTapped:(id)arg1 ;
-(void)setSecurePasscodeEntry:(BOOL)arg1 ;
-(id)initWithNumberOfEntryFields:(unsigned long long)arg1 ;
-(void)setFieldSpacing:(NSArray *)arg1 ;
-(BOOL)securePasscodeEntry;
-(NSArray *)fieldSpacing;
@end

