/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:08 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

@interface PSWeakReference : NSObject <NSCopying> {

	id _location;

}
+(id)weakReferenceWithObject:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long)hash;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)object;
-(id)forwardingTargetForSelector:(SEL)arg1 ;
-(id)initWithObject:(id)arg1 ;
@end

