/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:08 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@class NSArray;

@interface SuggestedAppsController : NSObject {

	NSArray* _specifiers;

}

@property (nonatomic,readonly) NSArray * specifiers;              //@synthesize specifiers=_specifiers - In the implementation block
-(NSArray *)specifiers;
-(void)reloadSpecifiers;
-(void)setMyApps:(id)arg1 specifier:(id)arg2 ;
-(id)myApps:(id)arg1 ;
@end

