/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:07 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol UIAppearance <NSObject>
@required
+(id)appearance;
+(id)appearanceWhenContainedInInstancesOfClasses:(id)arg1;
+(id)appearanceWhenContainedIn:(Class)arg1;
+(id)appearanceForTraitCollection:(id)arg1;
+(id)appearanceForTraitCollection:(id)arg1 whenContainedInInstancesOfClasses:(id)arg2;
+(id)appearanceForTraitCollection:(id)arg1 whenContainedIn:(Class)arg2;

@end

