/*
* This header is generated by classdump-dyld 0.7
* on Thursday, January 14, 2016 at 3:32:08 AM Eastern European Standard Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol UITextContentViewDelegate <NSObject>
@optional
-(void)textContentViewDidEndEditing:(id)arg1;
-(BOOL)textContentViewShouldBeginEditing:(id)arg1;
-(BOOL)textContentViewShouldEndEditing:(id)arg1;
-(BOOL)textContentView:(id)arg1 shouldScrollForPendingContentSize:(CGSize)arg2;
-(BOOL)textContentView:(id)arg1 shouldChangeSizeForContentSize:(CGSize)arg2;
-(void)textContentView:(id)arg1 didChangeSize:(CGSize)arg2;
-(BOOL)textContentView:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;
-(void)textContentViewDidChange:(id)arg1;
-(void)textContentViewDidChangeSelection:(id)arg1;
-(void)textContentViewDidBeginEditing:(id)arg1;

@end

